vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        voyage:
            uri_prefix: /images/voyages
            upload_destination: '%kernel.project_dir%/public/images/voyages'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
