#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# api/config/routes.yaml
authentication_token:
  path: /authentication_token
  methods: [POST]

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

login:
  path: /login
  controller: App\Controller\AuthController::login

api:
  path: /api
  controller: App\Controller\AuthController::api

login_check:
  path:     /login_check
  methods:  [POST]